name 'volgactf-public'
maintainer 'Alexander Pyatkin'
maintainer_email 'aspyatkin@gmail.com'
license 'MIT'
description 'Install and configure VolgaCTF public infrastructure'
version '0.0.4'

depends 'firewall', '~> 2.7'
depends 'vlt', '~> 0.2'
depends 'nodejs', '~> 7.0'
depends 'ngx', '~> 2.2'
depends 'ngx-modules', '~> 1.3'
depends 'logrotate', '~> 2.2'
depends 'dhparam', '~> 2.0'
depends 'redirect', '~> 4.0'
